### PR TITLE
updates to support quads in the release graph function

### PR DESCRIPTION
**Pull request by fils**
Changed include

* ADR: https://github.com/gleanerio/nabu/blob/dev/decisions/0001-URN-decision.md
* bulkloader  (both bulk and release) now checks if single file, skips skolimization if true.  Not needed with 
a single file since no chance for blank node URN collision
* example.yaml updated to include the context parameters and contextmap node
* comment removed in jsonldToNQ.go  (pointless to do, but I did it anyway)  ;) 
* mod ldproc.go to read and use the context map node in the config
* Makefile order changed, for no good reason
* pipcopy update to support quads as output
* skolemize.go comment removed to simply pad the number of files in the commit.  ;) 
* urnToPrefix   more pointless comment updates to make me feel good
* tofromRDF.go added which does some various RDF transforms, there are some unused functions in here (JsonldToNQ,NqToJSONLD,NqToNTCtx)  but left them in for now. 

So really only pipecopy, ldproc toFromRDF and the two bulkloader files have any changes of value in them.

### CODE REVIEW

**Review by valentinedwv — COMMENTED** [review]
Get this error... but file get's uploaded.
{"file":"/Users/valentin/development/dev_earthcube/gleanerio/nabu/internal/services/bulk/bulkLoader.go:54","func":"github.com/gleanerio/nabu/internal/services/bulk.BulkAssembly","level":"info","msg":"Put \"?graph=urn:gleaner:scratch:iris_bulk\": unsupported protocol scheme \"\"","time":"2023-03-02T12:25:10-08:00"}

**Comment by fils** [comment]
@valentinedwv   good catch, I didn't test the services-bulk as close as releases-bulk.

I'll look into it!

**Comment by fils** [comment]
@valentinedwv pushed updates to resolve (and hopefully improve) the bulk command that loads into the triplestores.  Docs updated to detail this.


- bulkLoader.go   cleaned up and viper read moved to the docfunc.go
- example.yaml    some clean up and generalizing then add in the endpointMethod and contentType params in sparql node
- function.go     trap errors better and cleanup, read new parameters in the config for different triplestores deprecated ioutils.ReadAll replaced with io.ReadAll
- README.md       doc updates
- sparql.go       update in pkg file to read in the new config parameters
- allGraphs.rq     testing query modified
- allLimit100.rq     testing query modified

**Review by valentinedwv — APPROVED** [review]
Works. 
Running a test using the branch in glcon testing, but can't see that it would fail.

**Comment by valentinedwv** [comment]
Maybe upload to latest without the datestamp on the filename?

**Pull request merged**
